### PR TITLE
Added ARN ignore functionality that reads from

### PR DESCRIPTION
**Pull request by dofinn**
/etc/openshift_tools/v4_arn_ignore.yaml

Due to V4 instances becoming available for access, the current aws_api_key_manager script falls over when it can not handled failed auth to these ARNs. Until  V4 access has a SOP, I propose we pass a config file that holds V4 ARNS that aws_api_key_manager will parse and ignore.

### CODE REVIEW

**Comment by dofinn** [comment]
Original error

```
Traceback (most recent call last):
  File "/usr/local/bin/aws_api_key_manager", line 492, in <module>
    MANAGE.main()
  File "/usr/local/bin/aws_api_key_manager", line 484, in main
    self.run_all(args, ops_accounts)
  File "/usr/local/bin/aws_api_key_manager", line 416, in run_all
    client = self.get_token(account_number)
  File "/usr/local/bin/aws_api_key_manager", line 258, in get_token
    idp_host=ops_idp_host
  File "/usr/lib/python2.7/site-packages/openshift_tools/saml_aws_creds.py", line 99, in get_temp_credentials
    SAMLAssertion=assertion)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithSAML operation: User null is not authorized to perform: sts:AssumeRoleWithSAML on resource: arn:aws:iam::359022075941:role/admin
```

Also looks like CI broken. 

```
[0mBranch stg set up to track remote branch stg from origin.
[91mSwitched to a new branch 'stg'
[0m[91mTraceback (most recent call last):
  File "/validator/openshift-tools/jenkins/test/run_tests.py", line 45, in <module>
    import github_helpers
  File "/validator/openshift-tools/jenkins/test/github_helpers.py", line 6, in <module>
    from github import Github
ImportError: No module named github
[0mRemoving intermediate container c58a3fd2aa20
error: build error: The command '/bin/sh -c mkdir /validator &&     git clone https://github.com/openshift/openshift-tools /validator/openshift-tools &&     cd /validator/openshift-tools &&     git checkout stg &&     git config user.name validator &&     git config user.email validator@localhost &&     /usr/bin/python /validator/openshift-tools/jenkins/test/run_tests.py' returned a non-zero code: 1
```

**Comment by dofinn** [comment]
[test]

**Comment by drewandersonnz** [comment]
[test]

**Review by rhdedgar — APPROVED** [review]
:+1: provided this has been tested already. Thanks for the update!

**Comment by dofinn** [comment]
>  provided this has been tested already. Thanks for the update!

```
[dofinn@bastion-nasa-1 ~]$ ./git/openshift-tools/scripts/iam-tools/aws_api_key_manager.py -p uhc-deployment-e2e-validation
Ignoring v4 resource: uhc-deployment-e2e-validation:359022075941
Checked for stamp file and it exists. No write was called, nothing to do here.
```

**Pull request merged**
