### PR TITLE
first pass at automating our verification process

### PR DESCRIPTION
**Pull request by stenwt**

### CODE REVIEW

**Comment by gburges** [comment]
+1

**Comment by detiber** [comment]
It might be a good thing to trigger a subset of the e2e/conformance tests.

@sdodson do you know the magic invocation they can use to trigger non-destructive e2e tests?

**Comment by sdodson** [comment]
No, @jayunit100 should be able to help determine the correct invocation. That said, I think the e2e tests create their own namespaces so they should be out of the way.

**Comment by jayunit100** [comment]
```
ginkgo.skip=Skipped|Disruptive|Slow|Flaky
```

and 

```
ginkgo.focus=Conformance
```

should do it for you

**Pull request closed without merging**
