### PR TITLE
Moved zabbix plot files to the right places

### PR DESCRIPTION
**Pull request by jgkennedy**

### CODE REVIEW

**Comment by kwoodson** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Comment by jgkennedy** [comment]
ok to test

**Pull request closed without merging**
