### PR TITLE
Adding new user ops_monitoring

### PR DESCRIPTION
**Pull request by mmahut**
Add new user ops_monitoring and generate its credential to a file.

### CODE REVIEW

**Comment by mmahut** [comment]
Related https://github.com/openshift/openshift-ansible-ops/pull/1804

**Comment by mwoodson** [comment]
I'm good with this.  I'd like other's to take a look.  +1 from me, but I'd like other +1. 

@twiest @ivanhorvath @kwoodson @joelddiaz Thoughts?

**Comment by ivanhorvath** [comment]
So this user would have different access level than the account owner? I thought we already can use that with boto from host monitoring container to grab info from aws. Is that not so?

**Comment by kwoodson** [comment]
@mmahut 
What's this user for?  I'm generally fine with adding him to the container if there is a good reason.  The location for the file seems fine.

I would definitely test and verify that the snapshotting continues to work when adding creds to this file.

**Comment by mmahut** [comment]
@kwoodson @ivanhorvath In my case this user will be used to check the state of the ELBs and report if any of the nodes is missing from the ELB and report it to zabbix. For my case, this user will have only read-only access to the ELB information (elasticloadbalancing:DescribeListeners) for now, however the idea is to add new policies to this user, once Joel reviews them, in case we need other access to AWS from the monitoring container (for example to monitor security groups etc).

**Pull request merged**
