### PR TITLE
Cron send metrics checks fix

### PR DESCRIPTION
**Pull request by superfunhappytime**
Added a work around to handle yaml.v2 package output of dates as strings

### CODE REVIEW

**Comment by superfunhappytime** [comment]
Hmm, somehow I've included another commit - fixing this MR

**Comment by superfunhappytime** [comment]
That's better. Ready for PR

**Comment by superfunhappytime** [comment]
failed pylint. fixing
C:115,23: Using type() instead of isinstance() for a typecheck. (unidiomatic-typecheck)

**Review by mrbarge — APPROVED** [review]

**Pull request merged**
