### PR TITLE
ohi: add 'wide' output that shows hostname, nodename, public ip, and private ip

### PR DESCRIPTION
**Pull request by dcbw**
Untested, but that's understandable since I have no permissions to run it from anywhere...

### CODE REVIEW

**Comment by dcbw** [comment]
hmm, not sure what I need to do about:

```
Ensuring stage branch also contains daeea5c120164d7b9c13bfea44cea4471e3f49e4
> /usr/bin/git branch -q -r --contains daeea5c120164d7b9c13bfea44cea4471e3f49e4
These commits are not in stage:
	daeea5c120164d7b9c13bfea44cea4471e3f49e4
```

**Comment by dcbw** [comment]
@rhdedgar any idea what I need to do to fix the validation tests?  Thanks!

**Comment by rhdedgar** [comment]
[test]

**Comment by rhdedgar** [comment]
@dcbw I've seen that type of failure before if the PR gets opened against prod instead of stg, and then later switched to stg. It looks like running a manual test refreshed this info, the commit is passing now.

**Comment by dcbw** [comment]
@rhdedgar thanks!

**Comment by kwoodson** [comment]
@dcbw, this code looks fine to me.

**Review by ivanhorvath — APPROVED** [review]

**Pull request merged**
