### PR TITLE
Add docker_storage_to_overlay2 roles

### PR DESCRIPTION
**Pull request by mbarnes**
I've made a good faith effort to get my overlay2 work into `openshift-ansible`, but so far [my pull request](https://github.com/openshift/openshift-ansible/pull/5216) has not attracted much attention from @sdodson or other developers.  I've asked several times for peer review or approval to merge and have gotten no response.  I assume this is simply because everyone is swamped.

Meanwhile, I've already used this code to deploy overlay2 to production: `starter-ca-central-1` last week, with other "starter" clusters soon to follow.

I'll keep trying to get this properly added to the product, but I'd like to get this code merged somewhere *now* (if only temporarily) so the [already-merged overlay2 transition playbook](https://github.com/openshift/openshift-tools/blob/stg/ansible/playbooks/adhoc/docker_storage_to_overlay2/docker_storage_to_overlay2.yml) is not left in its currently broken state.

Once it's in the product, these roles can be reverted from `openshift-tools`.

### CODE REVIEW

**Comment by mbarnes** [comment]
The `docker_storage_to_overlay2.yml` playbook has already been merged into `stg` but not `prod` (I didn't think it appropriate at the time until my [other PR](https://github.com/openshift/openshift-ansible/pull/5216) got accepted).  The merge conflict is easy to resolve.

**Review by twiest — CHANGES_REQUESTED** [review]
@mbarnes and I discussed this and he's going to continue to try to get this upstreamed.

He's also going to look into how hard it would be to upstream the playbook as well sot hat it's a complete solution.

**Comment by mbarnes** [comment]
Finally got some peer review in my [upstream PR](https://github.com/openshift/openshift-ansible/pull/5216) and I've incorporated the updates here.

However, the openshift-ansible team has come out [strongly against supporting playbooks that destroy storage](https://github.com/openshift/openshift-ansible/pull/5216#issuecomment-342271218).  They would prefer new nodes be provisioned with overlay2 storage already set up and existing devicemapper nodes retired, rather than attempting to convert the storage in place.

I see their point (and I think even agree with it), but for what I've been tasked with I plan to continue using this playbook+role.  So my work may land here after all, if it lands anywhere.

**Comment by twiest** [comment]
Hey @mbarnes,
    @sdodson, @brenton and I discussed this PR on an e-mail chain and because we want to be compliant with the online first effort, this PR will land sometime in the future (possibly modified).

I'll create a card so that this effort can be tracked and get prioritized.

Thanks for your efforts on this,
Thomas

**Comment by sdodson** [comment]
Got to this email after I got to the others, but I don't see a card, so
lets use
https://trello.com/c/IGCV4VRH/561-add-devicemapper-to-overlayfs-migration-playbook
unless i've missed another card

**Comment by mbarnes** [comment]
Superseded by #3411

**Pull request closed without merging**
