### PR TITLE
wrap 3scale dump for rhmi

### PR DESCRIPTION
**Pull request by jessesarn**
This was created in response to request for new tiered access command to perform a "3scale dump" of the managed instance of 3scale on RHMI clusters.
https://issues.redhat.com/browse/INTLY-5281

Sample output when running the command via devaccess: https://gist.github.com/jessesarn/b0473dda7b7f569bbe1415c21a79cf4b

### CODE REVIEW

**Comment by ciaran-byrne** [comment]
@jessesarn can we take another look at the failing tests?

**Comment by jessesarn** [comment]
I can't access the jenkins to look at any details.  When I try to go there, I get:
```
HTTP ERROR 404
Problem accessing /job/openshift-tools-testing/7195/. Reason:

    Not Found
```

**Comment by ciaran-byrne** [comment]
[test]

**Comment by ciaran-byrne** [comment]
ok to test

**Comment by jessesarn** [comment]
Per @mrbarge: Closing this PR and will submit a new one against stg as requested.

**Comment by mrbarge** [comment]
Closing this PR because I believe it's confusing the testing validation of #4330

**Pull request closed without merging**
