### PR TITLE
Change cloud scripts to use MetricSender instead of ZaggSender

### PR DESCRIPTION
**Pull request by zgalor**
Use MetricSender instead of ZaggSender in monitoring scripts

depends on #1747

### CODE REVIEW

**Comment by zgalor** [comment]
@twiest I got some import errors from pylint.
openshift_tools.cloud.aws, 
openshift_tools.cloud.gcp

I don't know if i should disable those.

**Comment by twiest** [comment]
@zgalor yes, it is fine to pylint disable those.

This is that rare case where we need to do it because the libs are not loaded on the box that runs jenkins / pylint.

We're in the process of fixing this, but for now, pylint disabling that check is fine.

**Comment by zgalor** [comment]
@twiest Done. PTAL

**Comment by zgalor** [comment]
@joelddiaz PTAL

**Review by twiest — APPROVED** [review]
@zgalor This looks great!

This is ready to merge right after our holiday freeze is lifted.

**Pull request merged**
