### PR TITLE
ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2

### PR DESCRIPTION
**Pull request by mwoodson**

### CODE REVIEW

**Comment by dbaker-arch** [comment]
+1

**Review by dbaker-arch — APPROVED** [review]

**Review by rhdedgar — CHANGES_REQUESTED** [review]
Can you run generate-containers.yml and commit the other files as well?

**Review by dbaker-arch — APPROVED** [review]
+1 thanks.

**Review by rhdedgar — APPROVED** [review]
:+1:

**Pull request merged**
