### PR TITLE
Support numeric values from ops-metric-client cli

### PR DESCRIPTION
**Pull request by zgalor**
stg - #2134 

cc @twiest

### CODE REVIEW

**Comment by zgalor** [comment]
@twiest @tiwillia bot issue?

**Comment by zgalor** [comment]
[test]

**Comment by tiwillia** [comment]
@kwoodson The error in the CI for this PR looks like the same error we investigated a week or two ago where pylint was missing from the oso-host-monitoring image.

**Comment by kwoodson** [comment]
@tiwillia, I don't think anyone has picked this up.  Pylint is still missing.

**Comment by zgalor** [comment]
@tiwillia @kwoodson @twiest any way to skip the tests and merge? 
This commit already passed CI in stg.

**Comment by tiwillia** [comment]
@zgalor I'm okay with skipping testing here, the testing passed in stg and the prod-specific parent check did pass here. I certainly don't have final say though, you'll want to confirm with @kwoodson or @twiest

**Comment by zgalor** [comment]
@twiest @kwoodson ?

**Comment by kwoodson** [comment]
@zgalor, @tiwillia, @twiest, I'm uncomfortable merging this without actually testing it in our container.

**Comment by zgalor** [comment]
[test]

**Comment by zgalor** [comment]
[test]

**Comment by twiest** [comment]
[test]

**Comment by twiest** [comment]
[test]

**Pull request merged**
