### PR TITLE
roles/docker_storage_setup: Support overlay2

### PR DESCRIPTION
**Pull request by mbarnes**
A new variable `dss_docker_storage_driver` determines whether to use the `devicemapper` or `overlay2` storage driver configuration.

For backward-compatibility, the variable defaults to `devicemapper`, but `overlay2` is the new recommendation.

This is https://github.com/openshift/openshift-tools/pull/2990 for `prod`.

### CODE REVIEW

**Comment by mbarnes** [comment]
retest this please

**Comment by mbarnes** [comment]
[test]

**Comment by mbarnes** [comment]
TIL merge commits are essential for the [ops git workflow](https://github.com/openshift/ops-sop/blob/master/v3/gitworkflow.asciidoc).  I generally don't like merge commits, but the commit hashes don't otherwise agree between `stg` and `prod`.

Worth a mention in the SOP?

**Comment by twiest** [comment]
@mbarnes um, you closed #2990. Did you mean to merge it instead?

**Comment by mbarnes** [comment]
> @mbarnes um, you closed #2990. Did you mean to merge it instead?

I generally merge manually from the CLI when I have "fixup" commits.  GitHub doesn't have an option to "auto-squash" (`git rebase -i --autosquash`) before merging.

**Review by twiest — APPROVED** [review]

**Pull request merged**
