### PR TITLE
Implement add_dynamic_metric for HawkSender

### PR DESCRIPTION
**Pull request by zgalor**
Implementation will create tagging rules (similar to config file "metadata_rules").

### Example:
**cron-send-network-metrics**, calling:
metric_sender.**add_dynamic_metric**("disc.network", "#OSO_NET_INTERFACE", ["tun0", "vethcf88663d", "eth0"])

will create the following tagging rules:
[ {"regex": "disc.network.*\\[tun0\\]", "tags": {"OSO_NET_INTERFACE": "tun0"}},
  {"regex": "disc.network.\*\\[vethcf88663d\\]", "tags": {"OSO_NET_INTERFACE": "vethcf88663d"}}, 
  {"regex": "disc.network.\*\\[eth0\\]", "tags": {"OSO_NET_INTERFACE": "eth0"}}]

Then, 6 calls to **add_metric** with the following pairs:
disc.network.in.bytes[tun0]:  66085550
disc.network.in.bytes[vethcf88663d]:  30809517
disc.network.in.bytes[eth0]:  2174481627
disc.network.out.bytes[tun0]:  68700631
disc.network.out.bytes[vethcf88663d]:  41424582
disc.network.out.bytes[eth0]:  8585515645

Will produce the following metric tags:
key:  node/example.host.com/disc.network.in.bytes[tun0]
tags: {'OSO_NET_INTERFACE': 'tun0'}

key:  node/example.host.com/disc.network.in.bytes[vethcf88663d]
tags: {'OSO_NET_INTERFACE': 'vethcf88663d'}

key:  node/example.host.com/disc.network.in.bytes[eth0]
tags: {'OSO_NET_INTERFACE': 'eth0' }

key:  node/example.host.com/disc.network.out.bytes[tun0]
tags: {'OSO_NET_INTERFACE': 'tun0'}

key:  node/example.host.com/disc.network.out.bytes[vethcf88663d]
tags: {'OSO_NET_INTERFACE': 'vethcf88663d'}

key:  node/example.host.com/disc.network.out.bytes[eth0]
tags: {'OSO_NET_INTERFACE': 'eth0' }

### CODE REVIEW

**Comment by zgalor** [comment]
@twiest PTAL. tests are not running for some reason...

**Comment by twiest** [comment]
[test]

**Comment by zgalor** [comment]
This is a rather ugly solution.
Refactoring all scripts that use add_dynamic_metric would be cleaner.
Question is does dynamic metric scripts contain crucial tagging data we need to filter by, or set triggers by in the near future.

@twiest @simon3z your thoughts on that?

**Comment by twiest** [comment]
The more I see this, the more I think we're going to have to.

The regex thing you're relying on here is simply a pattern we use, but it's not enforced. Which means that somewhere in our code base, I'm sure we have dynamic items that don't use that pattern, which means the regex wouldn't work for them.

I don't have an example right now, though.

**Comment by tiwillia** [comment]
It looks like the tests didn't run due to issue #2080 

PR #2090 should resolve the test failures once merged into stg.

**Comment by tiwillia** [comment]
Please re [test]

**Comment by tiwillia** [comment]
The test failures appear to be legitimate:
```
> /usr/bin/pylint --rcfile=jenkins/test/validators/.pylintrc openshift_tools/monitoring/hawk_sender.py
Pylint failed:
Pylint failed:
************* Module openshift_tools.monitoring.hawk_sender
I: 32, 0: Locally disabling too-many-arguments (R0913) (locally-disabled)
C: 92, 4: Invalid method name "update_tags_for_key_with_regex_rules" (invalid-name)
R: 92, 4: Method could be a function (no-self-use)
```

**Pull request closed without merging**
