### PR TITLE
OSD-5885 Introduce daemonset config image customization

### PR DESCRIPTION
**Pull request by mrbarge**
This PR updates the `daemonset_pods` role to turn the `openshift_daemonset_config_image` parameter into a configurable variable, `dsp_config_image`, rather than a statically-coded dockerhub image.

An update to the `daemonset_pods` tech profile in `openshift-ansible-ops` is now supplying this variable to the role. That PR must be approved alongside this one in order for the change to succeed: https://github.com/openshift/openshift-ansible-ops/pull/6144

Refs: [OSD-5885](https://issues.redhat.com/browse/OSD-5885)

### CODE REVIEW

**Comment by karthikperu7** [comment]
[test]

**Comment by mrbarge** [comment]
@mwoodson @mbarnes  could either of you please review this PR, in conjunction with https://github.com/openshift/openshift-ansible-ops/pull/6144 ?  (and commit `fc5697b488c7c2bca5c60377a84a2e23e3fad2bf` in ansible-private `stg`).

My plan is to test this on the `ded-stage-aws` cluster and verify everything works before promoting further.

I had a look at the failed test and it looks like that's a problem with Jenkins itself. Its python "setuptools" package used for running the tests is now too old (the "`egg_info for package pyjwt produced metadata for project name unknown`" is the crucial bit here, that's an "setuptools is old" issue). I can take a look at trying to fix that as a separate thing.

**Comment by mwoodson** [comment]
:+1:

**Pull request merged**
