### PR TITLE
require an INC field which is stored as a comment on digicert's side

### PR DESCRIPTION
**Pull request by stenwt**

### CODE REVIEW

**Comment by dak1n1** [comment]
:+1:

**Comment by stenwt** [comment]
ok to test

**Comment by stenwt** [comment]
ok to test

**Comment by stenwt** [comment]
ok to test

**Comment by stenwt** [comment]
[test]

**Comment by stenwt** [comment]
[test]

**Comment by joelddiaz** [comment]
[test]

**Comment by joelddiaz** [comment]
[test]

**Pull request closed without merging**
