### PR TITLE
Update pull requests with pending status as soon as possible

### PR DESCRIPTION
**Pull request by tiwillia**
These changes will move the responsibility of updating a pull request witha "pending" status to the jenkins pipeline. This ensures that the pull request is updated with a pending status as soon as possible.

This change will also ensure that if an unexpected error occurs during the testing process, the pull request will still be updated with a failure status rather than left in a pending state.

An additional change removes the title and body of pull requests from webhook data. This ensures that possible issues parsing unexpected characters in the body and title of a pull request cannot occur. In testing, I saw issues not just with JSON parsing the title and pull request, but also with passing the data to the Docker build, passing the data to the openshift build, and passing the data to the jenkins plugin.

Note that the changes in this pull request will not take affect until merged. I expect tests to fail for this pull request since I've changed the data being passed to the docker build. Tests should however work when submitting against prod after merged into stg.

### CODE REVIEW

**Comment by tiwillia** [comment]
@twiest @kwoodson this is ready for review when you have time.

A lot of refactoring was required to get this working right, but I think it was definitely worth the time and effort.

I've tested this in my environment with success.

**Comment by tiwillia** [comment]
Tests are failing, as expected, due to the name of the environment variable supplied to the build being changed:
```
Unable to load JSON data from $GITHUB_WEBHOOK_PAYLOAD
```

**Review by twiest — APPROVED** [review]

**Comment by twiest** [comment]
@tiwillia the bot didn't run against this PR, not sure why.

Will this PR fix that?

I went ahead and approved hoping so.

**Comment by tiwillia** [comment]
@twiest Tests did actually run for this PR (and the other you emailed me about), but the PR status was never updated with a link to the jenkins build. These changes will ensure that the PR is updated with a link to the build and if an unexpected error occurs during testing (like in these PRs), the PR will be updated with a "tests failed to run" status.

As for why the other PR failed, I'm investigating and will let you know.

**Pull request merged**
