### PR TITLE
Make oso-host-monitoring container CentOS compatible

### PR DESCRIPTION
**Pull request by mhutter**
see #2888

### CODE REVIEW

**Comment by joelddiaz** [comment]
[ok to test]

**Comment by joelddiaz** [comment]
[test]

**Comment by joelddiaz** [comment]
[test]

**Comment by joelddiaz** [comment]
[test]

**Comment by joelddiaz** [comment]
[test]

**Comment by blentz** [comment]
:+1:  not sure why jenkins isn't showing the right status, but the console output doesn't show any errors. I'm okay merging this.

**Comment by kwoodson** [comment]
[test]

**Comment by ivanhorvath** [comment]
it's not showing because user is not whitelisted and somewhere along the line that is getting checked

**Comment by kwoodson** [comment]
@ivanhorvath,
```
[0mWARN: User mhutter not in admin or org whitelist.
```

Wonder why that would cause it to not report its status though?  Seems like we need to revisit that.

**Pull request merged**
